[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "promotion"
dependencies = [
    "opencv-python==4.6.0.66",
]
dynamic = ["version", "description"]

[tool.poetry.scripts]
promotion = 'promotion.main:main'
